language: python
python:
    - "2.7"
cache:
    directories:
        - $HOME/.pip-cache/
services: mysql
env:
    - DJANGO=1.8.2 DJANGO_SETTINGS_MODULE="harshp.settings.settings"
install:
    - pip install django --download-cache $HOME/.pip-cache/
    - pip install -r harshp/requirements/requirements_test.txt --download-cache $HOME/.pip-cache/
    - pip install git+https://github.com/Brobin/django-seed
before_script:
    - mysql -e "SET GLOBAL wait_timeout = 36000;"
    - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"
    - mysql -e 'create database IF NOT EXISTS harshp_dot_com;'
    - python manage.py migrate
script:
    - coverage run --source=harshp manage.py test
after_success:
    - coveralls
notifications:
    slack: harshp:8NHozfKnZn2JpbnOElJjgisT
    email:
        - me@harshp.com
    on_success: always
    on_failure: always
